@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRvbGZvIEx1aXoiLCJjcGYiOiIwNjUuOTA5LjcxMC05OSIsImVtYWlsIjoiYWxmbm9yaUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTU4NjQ1ODU2NywiZXhwIjoxNjE4MDE2MTY3fQ.xMSveWgO3AQpdgaZpp7MpO7AmFZ6bRA3vN27qY3cjZ0

@specialToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRvbGZvIEx1aXogQWRtaW4iLCJjcGYiOiIxNzEuNDEyLjMxMC0zMCIsImVtYWlsIjoiYWRtaW4uYWxmbm9yaUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1ODY0NjIwNjksImV4cCI6MTYxODAxOTY2OX0.HAWIAjm_Qk4jI8xgY5LG6fWKH-T8hBlK_gynSmJ8m4M

@host=http://localhost:8089
@myCPF=065.909.710-99
@myCPF2=066.402.209-03
@specialCPF=153.509.460-56

#### STATUS

### Get status list
GET {{host}}/api/status/
Authorization: Bearer {{token}} 

### Get status by tag
GET {{host}}/api/status/tag/EV
Authorization: Bearer {{token}} 


#### PURCHASES

### Get purchases list
###filter={"code": "XYZ"}&search=056
###filter={"date": "2020-04-05T03:00:00.000Z"}
###sort={"date": "desc", "value": "desc"}
GET {{host}}/api/purchases?
Authorization: Bearer {{specialToken}}

### Get purchases list by cpf
GET {{host}}/api/purchases/cpf/{{myCPF2}}?sort={"date":"desc"}
Authorization: Bearer {{specialToken}}

### Get one purchases
GET {{host}}/api/purchases/5e973de8ad43b701b9026250
Authorization: Bearer {{specialToken}}

### Create purchases
POST {{host}}/api/purchases/create
Authorization: Bearer {{specialToken}} 
content-type: application/json

{
    "code": "ABC123456G",
    "cpf": "066.402.209-03",
    "date": "2020-02-05T03:00:00.000Z",
    "value": 3333.33
}

### Update purchases
PUT {{host}}/api/purchases/update/5e8f992787492403abec982b HTTP/1.1
Authorization: Bearer {{specialToken}} 
content-type: application/json

{
    "date": "2020-04-04T03:00:00.000Z",
    "value": 1234.55
}

### Delete purchases
DELETE {{host}}/api/purchases/delete/5e8f830cc1ce9f00dcb8f68d
Authorization: Bearer {{token}} 


#### USERS

### Get user from token
GET {{host}}/api/user/current
Authorization: Bearer {{token}}


### Get user cashback from token or query
GET {{host}}/api/user/cashback
Authorization: Bearer {{token}}

### Create user
POST {{host}}/api/auth/sign/up HTTP/1.1
content-type: application/json

{
    "name": "Special User",
    "email": "special@user.com",
    "cpf": "153.509.460-56",
    "password": "S3crt3t$",
    "passwordConfirm": "S3crt3t$"
}

### Login user
POST {{host}}/api/auth/sign/in HTTP/1.1
content-type: application/json

{
    "email": "admin.alfnori@gmail.com",
    "password": "S3crt3t$"
}