@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRvbGZvIEx1aXoiLCJjcGYiOiIwNjUuOTA5LjcxMC05OSIsImVtYWlsIjoiYWxmbm9yaUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTU4NjI3NTYwOCwiZXhwIjoxNjE3ODMzMjA4fQ.tC8gwCTEsjr7vSw_zzFq4XwlKCPJhyflljxuzM9-GBg
@specialToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU3BlY2lhbCBVc2VyIiwiY3BmIjoiMTUzLjUwOS40NjAtNTYiLCJlbWFpbCI6InNwZWNpYWxAdXNlci5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1ODYyODU5OTgsImV4cCI6MTYxNzg0MzU5OH0.I262JcLPjPtClw5l1GeydEqMV01STwAaeWC-Mp0TjP4

@host=http://localhost:8089

#### STATUS

### Get status list
GET {{host}}/api/status/
Authorization: Bearer {{token}} 

### Get status by tag
GET {{host}}/api/status/tag/EV
Authorization: Bearer {{token}} 


#### PURCHASES

### Get purchases list
GET {{host}}/api/purchases?sort={"date":"desc"}&filter={"code": "ABC"}
Authorization: Bearer {{token}} 

### Get purchases list by cpf
GET {{host}}/api/purchases/cpf/15350946056?sort={"date":"desc"}
Authorization: Bearer {{specialToken}} 

### Get one purchases
GET {{host}}/api/purchases/5e17a4f5034c4b01a6ce749d
Authorization: Bearer {{token}} 

### Create purchases
POST {{host}}/api/purchases/create
Authorization: Bearer {{token}} 
content-type: application/json

{
    "code": "ABC1234000",
    "cpf": "153.509.460-56",
    "date": "2020-04-04T03:00:00.000Z",
    "value": 3333.33
}

### Update purchases
PUT {{host}}/api/purchases/update/5e8c944e90e748004194b904 HTTP/1.1
Authorization: Bearer {{token}} 
content-type: application/json

{
    "code": "ABC1234560",
    "cpf": "50510242200",
    "date": "2020-04-04T03:00:00.000Z",
    "value": 5555.55
}

### Delete purchases
DELETE {{host}}/api/purchases/delete/5e17e0de2fc30704eaf2d001
Authorization: Bearer {{token}} 


#### USERS

### Get user from token
GET {{host}}/api/user/current
Authorization: Bearer {{specialToken}} 

### Create user
POST {{host}}/api/auth/sign/up HTTP/1.1
content-type: application/json

{
    "name": "Special User",
    "email": "special@user.com",
    "cpf": "153.509.460-56",
    "password": "S3crt3t$",
    "passwordConfirm": "S3crt3t$"
}

### Login user
POST {{host}}/api/auth/sign/in HTTP/1.1
content-type: application/json

{
    "email": "special@user.com",
    "password": "S3crt3t$"
}